


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Akish
 */


public class PharmacyManagement extends javax.swing.JFrame {

    DefaultTableModel defaultTableModel = new DefaultTableModel();
Connection con = null;
PreparedStatement pst = null;
ResultSet rs = null, rs2 = null;
    

    
    public PharmacyManagement() {
        initComponents();
        con = DataBase.database.ConnectDb();   
            Object columns[] = {"RefNo","Drug name","Drug Type","Quantity","Unit Price","Dose"};    
    defaultTableModel.setColumnIdentifiers(columns);
    jTable1.setModel(defaultTableModel);
    jTable1.setDefaultEditor(Object.class, null);
    loadData();

    }
    public void loadData()
    {
    String sql = "SELECT `RefNo`, `Drug name`, `Drug Type`, `Quantity`, `Unit Price`, `Dose` FROM `pharmacy mangment`";
    try{
    pst = con.prepareStatement(sql);
    rs = pst.executeQuery();
    Object columnData[] = new Object[6];
    while(rs.next()) {
        columnData[0] = rs.getInt("RefNo");
        columnData[1] = rs.getString("Drug name");
        columnData[2] = rs.getString("Drug Type");
        columnData[3] = rs.getInt("Quantity");
        columnData[4] = rs.getInt("Unit Price");
        columnData[5] = rs.getInt("Dose");
        defaultTableModel.addRow(columnData);
    }
}
       catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
            txtref.setText(null);
            cbose1.setSelectedIndex(-1);
            cbose2.setSelectedIndex(-1);
            txtquantity.setText(null);
            txtup.setText(null);
            txtdose.setText(null);
         
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbose1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdose = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtup = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbose2 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnexit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtref = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setText("Akish Pharmacy Management System ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setText("Welcome to");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cbose1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        cbose1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a selection", "Panadol", "Abacavir Sulfate", "Abarelix", "Abatacept", "Abciximab", "Abelcet", "Abilify", "Abraxane", "Acamprosate Calcium", "Acarbose", "Accolate", "Accretropin", "AccuNeb", "Accupril", "Accutane", "Acebutolol", "Aceon", "Acetadote", "Acetaminophen", "Acetic Acid", "Aci-Jel", "Aciphex", "Acitretin", "Aclovate", "Acrivastine and Pseudoephedrine", "Actemra", "Acthrel", "Acticin", "Actimmune", "Actiq", "Actisite", "Activase", "Activella", "Actonel", "Actos", "Acular", "Acular LS", "Acuvail", "Acyclovir", "Adacel", "Adagen", "Adalat CC", "Adalimumab", "Adapalene", "Adcirca", "Adderall", "Adderall XR", "Adefovir Dipivoxil", "Adenoscan", "Adenosine", "Adipex-P", "Adoxa", "Adrenalin", "AdreView", "Adriamycin PFS", "Advair Diskus", "Advair HFA", "Advicor", "Aerospan HFA", "Afinitor", "Afluria", "Agalsidase Beta", "Aggrastat", "Aggrenox", "Agrylin", "Ak-Fluor", "Akineton", "Alamast", "Albendazole", "Albenza", "Albumin, Human", "Albuminar", "Albuterol Sulfate", "Albuterol Sulfate Inhalation Aerosol", "Alcaine", "Alclometasone Dipropionate", "Aldactazide", "Aldactone", "Aldara", "Aldesleukin", "Aldomet", "Aldoril", "Aldurazyme", "Alefacept", "Alemtuzumab", "Alendronate Sodium", "Alesse", "Alfenta", "Alfentanil", "Alfuzosin HCl", "Alglucosidase Alfa", "Alimta", "Alinia", "Alitretinoin", "Alkeran", "Allegra", "Allegra-D", "Allegra D 24 Hour", "Allernaze", "Alli", "Allopurinol", "Almotriptan Malate", "Alocril", "Alomide", "Aloprim", "Alora", "Alosetron Hydrochloride", "Aloxi", "Alphanate", "Alprazolam", "Alprostadil", "Alrex", "Alsuma", "Altabax", "Altace", "Alteplase", "Altocor", "Altoprev", "Altretamine", "Alupent", "Alvesco", "Amantadine Hydrochloride", "Amaryl", "Ambien", "Ambien CR", "Ambisome", "Amerge", "Americaine", "Amevive", "Amicar", "Amifostine", "Amikacin", "Amikin", "Amiloride", "Amiloride and Hydrochlorothiazide", "Amiloride Hydrochloride", "Amino Acids", "Aminocaproic Acid", "Aminoglutethimide", "Aminohippurate Sodium", "Aminolevulinic Acid", "Aminosalicylic Acid", "Aminosyn II 8.5%", "Aminosyn II in Dextrose", "Amitiza", "Amitriptyline", "Amlexanox", "Amlodipine Besylate", "Amoxapine", "Amoxicillin", "Amoxicillin Clavulanate", "Amoxil", "Amphadase", "Amphetamine", "Amphotericin B", "Ampicillin", "Ampyra", "Amrix", "Amyl Nitrite", "Amytal Sodium", "Anabolic steroids", "Anadrol-50", "Anafranil", "Anagrelide", "Anakinra", "Anastrozole", "Ancobon", "Androderm", "AndroGel", "Anectine", "Angeliq", "Angiomax", "Anidulafungin", "Anisindione", "Ansaid", "Antabuse", "Antara", "Anthralin", "Antihemophilic Factor", "Antithrombin", "Antivenin", "Antivert", "Antizol", "Anturane", "Anusol Hc", "Aphthasol", "Apidra", "Aplenzin", "Apokyn", "Apomorphine", "Apraclonidine", "Apresazide", "Apresoline", "Apri", "Apriso", "Aprotinin", "Aptivus", "Aquasol A", "Aralen", "Aramine", "Aranesp", "Arava", "Arcalyst", "Aredia", "Argatroban", "Aricept", "Arimidex", "Aripiprazole", "Aristocort", "Arixtra", "Armodafinil", "Aromasin", "Arranon", "Artane", "Arthrotec", "Arzerra", "Asacol", "Asacol HD", "Asclera", "Ascorbic Acid", "Asmanex Twisthaler", "Asparaginase", "Aspirin", "Astelin", "Astemizole", "Astepro", "Atacand", "Atacand HCT", "Atazanavir Sulfate", "Atenolol and Chlorthalidone", "Atgam", "Ativan", "Atomoxetine HCl", "Atorvastatin Calcium", "Atovaquone", "Atracurium Besylate", "Atralin", "Atridox", "Atripla", "Atromid-S", "Atropen", "Atropine", "Atrovent HFA", "Atryn", "Augmentin", "Augmentin XR", "Auralgan", "Avage", "Avalide", "Avandamet", "Avandaryl", "Avandia", "Avapro", "Avastin", "Avelox", "Avinza", "Avodart", "Avonex", "Axert", "Axid", "Aygestin", "Azacitidine", "Azasan", "Azasite", "Azathioprine", "Azelaic Acid", "Azelastine Hydrochloride", "Azelex", "Azilect", "Azithromycin", "Azmacort", "Azopt", "Azor", "Azulfidine EN-Tabs" }));
        cbose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbose1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quantity");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Drug Name");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Dose");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtupActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Unit price");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Drug Type");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbose2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        cbose2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a selection", "Tablet", "Liquid", "Capsules", "Topical medicines", "Suppositories", "Drops", "Inhalers", "Injections", "Implants or patches", " " }));

        btnexit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnadd.setText("Add");
        btnadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddMouseClicked(evt);
            }
        });
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateMouseClicked(evt);
            }
        });
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ref.NO", "Drug Name", "Drug Type", "Quantity", "Unit price", "Dose"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Reference Number");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbose1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbose2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtref, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdose, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(529, 529, 529)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                    .addComponent(txtup, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(77, 77, 77)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtref, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(231, 231, 231)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtup, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(618, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtupActionPerformed

    private void cbose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbose1ActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        frame = new JFrame("Exit");
        if  (JOptionPane.showConfirmDialog(frame, "Cofirm if you want to exit","Akish Pharmacy Management System ",JOptionPane.YES_NO_OPTION ) ==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       
       if (jTable1.getSelectedRow()==-1){
           if(jTable1.getRowCount()==0){
               JOptionPane.showMessageDialog(null, "No data to delete","Pharmacy Management system",JOptionPane.OK_OPTION);
          }else {
               JOptionPane.showMessageDialog(null,"Select a row to delete ","Pharmacy Management system",JOptionPane.OK_OPTION);
               
           }
           
       }else{
                   model.removeRow(jTable1.getSelectedRow());
                   }
           
       
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtup.setText("");
        txtdose.setText("");
        txtquantity.setText("");
        txtref.setText("");
        cbose1.setSelectedItem("");
        cbose2.setSelectedItem("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed

    }//GEN-LAST:event_btnaddActionPerformed

    private void txtrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrefActionPerformed

    private void btnaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseClicked
        int ref = Integer.parseInt(txtref.getText());
        String dname = cbose1.getSelectedItem().toString();
        String dtype = cbose2.getSelectedItem().toString();
        int quantity = Integer.parseInt(txtquantity.getText());
        int uprice = Integer.parseInt(txtup.getText());
        int dose = Integer.parseInt(txtdose.getText());
        if( dname.equals("") || dtype.equals(""))
            {
            
                JOptionPane.showMessageDialog(null, "Complete Your Information", "Missing Information", 2);
                
            }
        else{
            String sql = "INSERT INTO `pharmacy mangment`(`RefNo`, `Drug name`, `Drug Type`, `Quantity`, `Unit Price`, `Dose`) VALUES (?,?,?,?,?,?)";
            if(con != null){
        try {
   
           pst = con.prepareStatement(sql);
           pst.setInt(1, Integer.parseInt(txtref.getText()));
           pst.setString(2, (String) cbose1.getSelectedItem());
           pst.setString(3, (String) cbose2.getSelectedItem());
           pst.setInt(4,Integer.parseInt(txtquantity.getText()));
           pst.setInt(5,Integer.parseInt(txtup.getText()));
           pst.setInt(6,Integer.parseInt(txtdose.getText()));
            
            pst.execute();
            defaultTableModel.getDataVector().removeAllElements();
                    defaultTableModel.fireTableDataChanged();
                    loadData();
                    this.dispose();
                    new PharmacyManagement().setVisible(true);
                    JOptionPane.showMessageDialog(null, "Your Data updated Successfully !");
            
    }           catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                    
                }
    
        }
        }

    }//GEN-LAST:event_btnaddMouseClicked

    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
        // TODO add your handling code here:
        int ref = Integer.parseInt(txtref.getText());
        String dname = cbose1.getSelectedItem().toString();
        String dtype = cbose2.getSelectedItem().toString();
        int quantity = Integer.parseInt(txtquantity.getText());
        int uprice = Integer.parseInt(txtup.getText());
        int dose = Integer.parseInt(txtdose.getText());
        if( dname.equals("") || dtype.equals(""))
            {
            
                JOptionPane.showMessageDialog(null, "Complete Your Information", "Missing Information", 2);
                
            }
        else{
            String sql = "UPDATE `pharmacy mangment` SET `RefNo`='"+ref+"',`Drug name`='"+dname+"',`Drug Type`='"+dtype+"',`Quantity`='"+quantity+"',`Unit Price`='"+uprice+"',`Dose`='"+dose+"' WHERE RefNo ='"+ref+"'";
            if(con != null){
        try {
   
           pst = con.prepareStatement(sql);
            
            pst.execute();
            defaultTableModel.getDataVector().removeAllElements();
                    defaultTableModel.fireTableDataChanged();
                    loadData();
                    this.dispose();
                    new PharmacyManagement().setVisible(true);
                    JOptionPane.showMessageDialog(null, "Your Data updated Successfully !");
            
    }           catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                    
                }
    
        }
        }
        
    }//GEN-LAST:event_btnupdateMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        int row = jTable1.getSelectedRow();
        txtref.setText(jTable1.getValueAt(row, 0).toString());
        cbose1.setSelectedItem(jTable1.getValueAt(row, 1).toString());
         cbose2.setSelectedItem(jTable1.getValueAt(row, 2).toString());
         txtquantity.setText(jTable1.getValueAt(row, 3).toString());
         txtup.setText(jTable1.getValueAt(row, 4).toString());
         txtdose.setText(jTable1.getValueAt(row, 5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private JFrame frame;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacyManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbose1;
    private javax.swing.JComboBox<String> cbose2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtdose;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txtref;
    private javax.swing.JTextField txtup;
    // End of variables declaration//GEN-END:variables
}
